# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty

title: Raphael Gruber
tagline: "A Jekyll theme"
description: "A Software Developer writing to educate himself."
url: https://raphaelgruber.me
baseurl: /

paginate: 5

remote_theme: poole/hyde
