baseURL = "https://coding-artisan.blog/"
languageCode = "en-us"
title = "Coding Artisan"
theme = "m10c"
publishDir = "docs"
author = "Raphael Gruber"
description = "On microservices, testing and the daily life of a software engineer"

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/raphi011"

[[params.social]]
  icon = "twitter"
  name = "My Twitter"
  url = "https://twitter.com/raphi011"